const ACTIVATION_LINK_WILL_EXPIRE_IN = 24 * 60 * 60 * 1000; // 24 hours

const MAX_FILE_SIZE_IN_MB = 5;

const MAX_NUMBER_OF_FILES = 10;

module.exports = {
    ACTIVATION_LINK_WILL_EXPIRE_IN,
    MAX_FILE_SIZE_IN_MB,
    MAX_NUMBER_OF_FILES,
};
